apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: swiftcart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: swiftcart/notification-service:local
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 3003
          envFrom:
            - configMapRef:
                name: swiftcart-config
            - secretRef:
                name: swiftcart-secret
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"